name: flutternotifi
description: "A Flutter project with MongoDB integration, notifications, and music playback."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  mongo_dart: ^0.9.0
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Song.mp3
